### PR TITLE
Support multiple calls of same command.

### PR DESCRIPTION
**Pull request by TheOnly92**
Support multiple calls of the same command to allow drawing of polygons. For example:

```
el.beginPath();
el.moveTo(0,0);
el.lineTo(100,100);
el.lineTo(100,50);
el.closePath();
el.fill();
```

### CODE REVIEW

**Comment by RSamaium** [comment]
Hello,

To draw lines, it is very useful but CanvasEngine uses a command and ignores the previous one:

```
el.drawImage("foo");
el.drawImage("bar");
```

Here, the image changes and removes the previous image. Important for animations. I think that there should be a property to allow multiple commands an element. Example : 

```
el.multiple = true;
el.beginPath();
el.moveTo(0,0);
el.lineTo(100,100);
el.lineTo(100,50);
el.closePath();
el.fill();
```

**Comment by TheOnly92** [comment]
Thanks for the reply. I suppose, then, it's a matter of making which method implicit, i.e. do you have to specifically say that you want to run multiple commands or whether you have to specify that you want to replace previous commands.

In my opinion, automatically replacing the previous command doesn't seem too logical in game programming (or 3D programming), and it might also introduce some unexpected bugs or frustrations especially when trying to draw a polygon.

But well, in the end it will be your decision since it's your project, I'll try to modify based on your request if you insist it.

**Comment by RSamaium** [comment]
Or so, there should be an exception for drawing polygons. 
If you want to draw multiple images, it could insert an array in parameters : 

```
el.drawImage(["foo", "bar"]);
```

This is just a guess.

**Comment by TheOnly92** [comment]
Well actually, I couldn't really suggest a better way of doing things here.

You have a `removeCmd` command to discard the previous image, but if it breaks things...

**Pull request merged**
